export const serviceData = [
  {
    serviceId: 1,
    serviceName: "Pool Products",
    serviceDesc:
      "Welcome to Shreeji, your premier swimming pool consultancy company specializing in designing, constructing, and maintaining stunning swimming pools. We take pride in offering a comprehensive range of pool products and equipment to ensure the highest level of enjoyment and safety for our clients. With our expertise and commitment to excellence, we are your trusted partner in creating exceptional aquatic spaces.",
  },
  {
    serviceId: 2,
    serviceName: "Media changing",
    serviceDesc:
      "At Shreeji, we believe that a well-maintained pool is the centerpiece of any luxurious oasis. We know that achieving pristine water quality can sometimes feel like an endless battle, but with our advanced media changing solutions, it's a battle you can win effortlessly Media changing is the process of periodically replacing the filter media within your pool filtration system. Over time, the media can become saturated with impurities, hindering its ability to effectively remove debris and maintain water clarity. This can lead to reduced circulation, increased chemical consumption, and a dull swimming experience. However, with our state-of-the-art filtration systems and expert guidance, media changing becomes a breeze. But what sets Shreeji apart is our commitment to sustainability. We understand the importance of protecting the environment while providing exceptional service. That's why our media changing solutions emphasize eco-friendly alternatives. By utilizing advanced filter media options such as recycled glass, zeolite, or diatomaceous earth, we help reduce waste and minimize the ecological impact, all without compromising on water quality. When you choose Shreeji as your swimming pool consultancy partner, you're not just investing in a filtration system – you're embracing a new era of effortless pool maintenance. Our team of experts will guide you through every step of the media changing process, ensuring that your pool remains a sparkling oasis of joy and relaxation. Don't let outdated filtration methods hold you back. Embrace the future of pool maintenance with Shreeji. Contact us today to discover how our media changing solutions can transform your swimming experience and elevate your pool to new heights of clarity and beauty.",
  },
  {
    serviceId: 3,
    serviceName: "Complete line of pool chemicals",
    serviceDesc:
      "Welcome to Shreeji, your trusted partner in swimming pool consultancy and cutting-edge pool filtration systems. As experts in pool care, we understand that maintaining a healthy and sparkling pool requires the right combination of expertise, technology, and high-quality pool chemicals. That's why we're delighted to offer you a comprehensive range of premium pool chemicals that will keep your pool water pristine, inviting, and safe for all swimmers. We have many types of chemicals such as TCCA90, copper sulphate, alum, magic powder, etc.",
  },
  {
    serviceId: 4,
    serviceName: "Consultancy for cleaning",
    serviceDesc:
      "At shreeji we provide you expert consultancyfor maintaining your pool easily. We can help you virtually after getting full knowledge of the problems. Our team expert will provide correct and right way to keep your pool clean. As a result using our method of cleaning will keep your pool free from any type of problem.",
  },
  {
    serviceId: 5,
    serviceName: "Problem and solutions",
    serviceDesc:
      "Discover Your Pool's Perfect Solution with Shreeji. Our pool consultancy services specialize in identifying your pool's unique challenges and providing tailored solutions. With our expertise in swimming pool maintenance and filtration systems, we assess your pool's needs and develop personalized plans of action. From water quality issues to equipment malfunctions, we leave no stone unturned in delivering effective solutions. Trust Shreeji to transform your pool into a trouble-free oasis that exceeds your expectations. Contact us today for a consultation and let us be your partner in finding the perfect solutions for your pool.",
  },
  {
    serviceId: 6,
    serviceName: "Pool Lights",
    serviceDesc:
      "At Shreeji, we also provide swimming pool lights that will transform your pool into a mesmerizing oasis, perfect for nighttime swims and entertaining. We understand that lighting plays a vital role in enhancing the ambiance and safety of your pool, which is why we provide top-quality pool lights that combine style, durability, and functionality. Not only our pool lights enhance the aesthetics of your pool, but they also provide practical benefits. They improve visibility and safety during nighttime swimming, allowing you to enjoy your pool with peace of mind. Our lights are built to withstand the rigors of outdoor environments and are resistant to water and UV damage, ensuring long-lasting performance and durability. Installation of our swimming pool lights is hassle-free, and our team of experts is available to assist you every step of the way.our professional technicians can handle the installation process, ensuring a seamless and efficient setup. Whether you want to create a serene and tranquil atmosphere or a vibrant and lively setting, our swimming pool lights will exceed your expectations. With their energy efficiency and long lifespan, they are not only a visually appealing addition to your pool but also a cost-effective investment. Choose Shreeji for exceptional swimming pool lights that will elevate the beauty and functionality of your pool, allowing you to create unforgettable memories and enjoy nighttime swims in style. ",
  },
  {
    serviceId: 7,
    serviceName: "Ladders",
    serviceDesc:
      "At Shreeji, we understand the importance of easy access and safety when it comes to enjoying your swimming pool. That's why we offer a range of high-quality pool ladders designed to provide a secure and convenient way to enter and exit your pool. Our pool ladders are crafted with the highest standards of quality and durability. Built to withstand the elements and constant use, they are made from corrosion-resistant materials, ensuring long-lasting performance even in outdoor environments. With sturdy construction and non-slip steps, our ladders provide stability and peace of mind for swimmers of all ages. We offer various sizes of pool ladders to suit different pool designs and preferences. From traditional A-frame ladders to stylish and sleek stainless steel ladders, we have options to match your pool's aesthetics and functional requirements. Our ladders are available in different sizes and configurations, making it easy to find the perfect fit for your pool. Not only do our pool ladders provide a safe means of entry and exit, but they also enhance the overall pool experience. They make it easier for swimmers to get in and out of the water, allowing for more time to be spent enjoying your pool. Whether you have an above-ground or in-ground pool, our expert team will assist you in selecting the ideal ladder that meets your specific needs. Invest in a high-quality pool ladder from Shreeji and ensure the accessibility and safety of your swimming pool. With our reliable and stylish ladders, you can create a welcoming and enjoyable environment for family and friends to relax and have fun. ",
  },
  {
    serviceId: 8,
    serviceName: "Mosaic Tiles",
    serviceDesc:
      "At Shreeji, we offer a stunning collection of swimming pool mosaic tiles that will elevate the aesthetic appeal of your pool and create a truly captivating visual experience. We understand that the right choice of tiles can make a significant difference in the overall look and ambiance of your pool, which is why we provide an extensive range of high-quality mosaic tiles designed specifically for swimming pools. Our swimming pool mosaic tiles are crafted with precision and attention to detail, showcasing exquisite designs and vibrant colors. Whether you prefer a classic and timeless look or a modern and bold statement, we have a wide variety of styles, patterns, and sizes to suit your individual taste and complement your pool's design. Our knowledgeable team is available to guide you through the selection process, helping you choose the perfect mosaic tiles that reflect your personal style and enhance the unique character of your pool. We source our tiles from reputable manufacturers known for their quality craftsmanship and innovative designs, ensuring that you receive only the finest products. Installing our swimming pool mosaic tiles is a breeze, and we can recommend experienced professionals who specialize in pool tile installations to ensure a flawless and seamless finish. Transform your pool into a work of art with our exquisite mosaic tiles. Let the shimmering colors and intricate designs create a captivating visual display that will leave a lasting impression on your guests. With Shreeji's swimming pool mosaic tiles, you can turn your pool into a stunning masterpiece ",
  },
  {
    serviceId: 9,
    serviceName: "Pool Liners",
    serviceDesc:
      "At Shreeji, we offer premium swimming pool liners that can completely transform the look and feel of your pool. Our pool liners not only enhance the aesthetics but also provide essential protection for your pool structure, ensuring long-lasting durability and enjoyment. Our pool liners are crafted from high-quality materials that are specifically designed to withstand the harsh conditions of pool environments. Whether you have an above-ground or in-ground pool, our liners are engineered to resist fading, tearing, and punctures, providing a reliable and low-maintenance solution for years to come. Not only do our pool liners enhance the appearance of your pool, but they also provide an additional layer of protection. The liner acts as a barrier between the water and the pool structure, preventing leaks, cracks, and corrosion. This helps to extend the lifespan of your pool and reduce maintenance costs over time. Installing a new pool liner is a straightforward process with the help of our professional team. We have experience working with pools of all shapes and sizes, ensuring a precise and seamless fit. Our goal is to provide you with a hassle-free installation experience and a pool that looks brand new. Experience the difference a high-quality pool liner can make for your swimming pool. Choose Shreeji for durable and customizable liners that will transform your pool into a stunning oasis, while offering protection and peace of mind. ",
  },
  {
    serviceId: 10,
    serviceName: "Replacement Parts",
    serviceDesc:
      "At Shreeji, we understand the importance of keeping your swimming pool in top-notch condition. That's why we offer a wide selection of high-quality replacement parts to help you maintain and repair your pool with ease. Whether you're a pool owner, a maintenance professional, or a contractor, we have the parts you need to keep your pool running smoothly.Our range of replacement parts covers various components of your swimming pool, including pumps, filters, valves, heaters, lights, and more. We source our parts from reputable manufacturers known for their reliability and durability, ensuring that you receive products that meet the highest quality standards. Finding the right replacement part for your pool can be a hassle, but our knowledgeable team is here to assist you every step of the way. We'll help you identify the exact part you need, providing you with expert guidance and support to ensure a seamless replacement process. We understand that a malfunctioning pool component can disrupt your swimming experience or even affect the safety of your pool. That's why we strive to keep a comprehensive inventory of replacement parts in stock, allowing us to quickly fulfill your orders and minimize any downtime for your pool. By choosing Shreeji for your replacement parts, you can have peace of mind knowing that you're investing in reliable products that will help extend the lifespan of your pool equipment. Whether it's a simple gasket, a motor, a valve, or any other part, we've got you covered. Keep your pool performing at its best with top-quality replacement parts from Shreeji. Browse our extensive catalog or contact our team today to find the perfect replacement part for your swimming pool. ",
  },
  {
    serviceId: 11,
    serviceName: "Gratings",
    serviceDesc:
      "At Shreeji, we offer a wide selection of premium gratings designed to enhance both the safety and aesthetics of your swimming pool area. Our high-quality gratings provide a functional and stylish solution to ensure the smooth flow of water, while also preventing slips, trips, and other accidents. Safety is our utmost priority, and our pool gratings are specifically engineered to offer reliable slip resistance, providing a secure surface for swimmers and poolside visitors. Constructed from durable materials, our gratings are resistant to corrosion, UV rays, and chemicals typically found in pool environments, ensuring long-lasting performance and peace of mind. In addition to their practical function, our gratings are available in various designs, patterns, and finishes, allowing you to choose the option that complements your pool's aesthetics. Whether you prefer a sleek and modern look or a more traditional style, our range of gratings can effortlessly blend in or stand out as a striking design element in your pool area. Our expert team can assist you in selecting the right grating size, shape, and material that suits your pool's specifications and design vision. We work with top manufacturers known for their commitment to quality, ensuring that you receive gratings that are not only functional but also visually appealing. By investing in high-quality gratings from Shreeji, you can create a safe and visually stunning pool area that meets the highest standards of both functionality and aesthetics. Let our gratings be the finishing touch that elevates your swimming pool to a new level of elegance and safety.",
  },
  {
    serviceId: 12,
    serviceName: "Consultation",
    serviceDesc:
      "At Shreeji, we offer professional swimming pool consultancy services to help you turn your pool dreams into a stunning reality. Whether you're a homeowner, a property developer, or a business owner, our experienced team of consultants is here to provide you with expert guidance and support throughout the entire process. Our swimming pool consultancy services are tailored to meet your unique needs and vision. We understand that every project is different, and we take the time to listen to your ideas, understand your requirements, and assess the feasibility of your plans. From the initial concept and design phase to the construction and final implementation, we are dedicated to ensuring that your swimming pool project exceeds your expectations. Our team of skilled consultants brings a wealth of knowledge and experience in the swimming pool industry. We stay updated with the latest trends, technologies, and best practices to provide you with innovative and practical solutions. Whether you're looking for a luxurious residential pool, a commercial pool for a resort or hotel, or a community pool for a housing development, we have the expertise to make your vision a reality. Throughout the consultancy process, we work closely with you, offering valuable insights, creative design ideas, and technical expertise. We assist with site evaluations, budget planning, permit acquisition, contractor selection, and project management, ensuring a seamless and successful implementation. Our goal is to create a pool that not only meets your functional needs but also reflects your style and enhances the aesthetics of your space. At Shreeji, we believe that a well-designed and professionally executed swimming pool can be a transformative addition to any property. It can become a centerpiece for relaxation, entertainment, and creating lasting memories. With our swimming pool consultancy services, you can have peace of mind knowing that you're working with a dedicated team that is committed to delivering excellence and exceeding your expectations. Ready to bring your swimming pool vision to life? Contact Shreeji today to schedule a consultation and discover how our expertise can transform your pool dreams into a breathtaking reality. ",
  },
  {
    serviceId: 13,
    serviceName: "Pump and Filters",
    serviceDesc:
      "Pump and filters -At Shreeji, we understand that a clean and well-maintained swimming pool is the key to an enjoyable and refreshing experience. That's why we offer a wide range of high-quality swimming pool pumps and filters designed to keep your pool water crystal clear and pristine. Our pool pumps are engineered for efficiency and durability, ensuring optimal circulation and filtration of water. With their powerful motor and advanced technology, they effectively remove debris, dirt, and impurities, keeping your pool water clean and inviting.  In addition to pumps, we provide a variety of pool filters that play a crucial role in maintaining water quality. Our filters effectively trap and remove contaminants ensuring that your pool water remains clear and free from impurities. We offer different types of filters, including sand filters, cartridge filters, trolly filter, pipeless filter, allowing you to choose the option that best suits your pool's needs. Whether you have a residential pool, a commercial facility, or a community swimming pool, our expert team will help you select the right pump and filter combination to meet your specific requirements. We take pride in offering reliable products from top brands in the industry, ensuring long-lasting performance and customer satisfaction. Don't compromise on the quality of your pool water. Choose Shreeji for efficient swimming pool pumps and filters that deliver sparkling clean water, creating an inviting oasis for you and your guests to enjoy. ",
  },
  {
    serviceId: 14,
    serviceName: "Jacuzzi",
    serviceDesc:
      "At Shreeji, we offer expert jacuzzi consultation and design services to help you create a truly luxurious and relaxing retreat in your own space. Our team of experienced consultants understands the intricacies of jacuzzi installation and customization, and we are dedicated to bringing your vision to life. Our jacuzzi consultation services begin with a comprehensive assessment of your space, taking into consideration factors such as available area, layout, and your specific requirements and preferences. We work closely with you to understand your desired aesthetic, functionality, and budget, ensuring that every aspect is carefully considered during the design process. With our in-depth knowledge of jacuzzi technologies and trends, we guide you in selecting the perfect jacuzzi that meets your needs. Whether you desire a compact jacuzzi for intimate settings or a larger one for entertaining guests, we have a wide range of options to choose from, including various sizes, shapes, and features. We only partner with reputable manufacturers known for their quality and reliability, ensuring that you receive a jacuzzi of the highest standards. Our expertise extends beyond jacuzzi selection. We also provide guidance on jacuzzi placement, installation requirements, and maintenance considerations. Our team is well-versed in local regulations and safety guidelines, ensuring that your jacuzzi installation adheres to all necessary standards. With Shreeji's jacuzzi consultation services, you can be confident that your jacuzzi will be seamlessly integrated into your space, creating a tranquil and indulgent oasis that meets your expectations. We prioritize attention to detail and quality craftsmanship, resulting in a jacuzzi that not only looks stunning but also provides long-lasting performance and enjoyment. Whether you are a homeowner, a hotelier, or a commercial property owner, our jacuzzi consultation services are tailored to your specific needs. We are committed to delivering exceptional customer service and exceeding your expectations at every stage of the consultation and design process. Unlock the potential of your space and indulge in the ultimate relaxation with our expert jacuzzi consultation and design services. Contact us today to schedule a consultation and let us help you create the jacuzzi of your dreams. ",
  },
  {
    serviceId: 15,
    serviceName: "Fountains",
    serviceDesc:
      "At Shreeji, we offer professional fountain consultation services to help you bring the enchanting beauty of water features into your space. Our experienced team of consultants understands the art and science of fountain design, and we are dedicated to creating captivating water features that enhance the aesthetics and ambiance of any environment. Fountains have a magical quality that can transform an ordinary space into something extraordinary. Whether you are looking to add a fountain to your residential garden, commercial plaza, or public park, our fountain consulting services will guide you through the process, ensuring that your vision becomes a reality. Our fountain consultants will work closely with you to understand your goals, preferences, and the unique characteristics of your space. We will assess the site, considering factors such as size, location, and surrounding elements, to determine the most suitable fountain design that harmonizes with the overall environment. From elegant and classic styles to modern and avant-garde designs, we have the expertise to create fountains that truly make a statement. We provide comprehensive guidance on every aspect of fountain design, including the selection of materials, water flow patterns, lighting options, and integration of special features such as water jets, cascades, or interactive elements. Our team stays up to date with the latest trends and innovations in fountain design, ensuring that we deliver cutting-edge solutions that meet your expectations. With our fountain consultation services, you can expect meticulous attention to detail, personalized recommendations, and a focus on delivering a fountain that surpasses your imagination.  Whether you desire a tranquil and serene fountain or a dynamic and awe-inspiring display, our consultants will guide you in choosing the right fountain design that suits your preferences and space. We are committed to creating water features that captivate, inspire, and become a focal point of admiration. Trust Shreeji for expert fountain consultation services that will transform your space into a haven of beauty, serenity, and water-inspired artistry. ",
  },
  {
    serviceId: 16,
    serviceName: "Steam and Sauna",
    serviceDesc:
      "At Shreeji, we offer comprehensive consultation services for steam rooms and saunas, helping you design and create your own personal retreat of tranquility. We understand the transformative power of steam and sauna experiences in promoting relaxation, detoxification, and overall well-being. With our expertise, we will guide you through every step of the process, ensuring that you achieve the perfect steam and sauna setup tailored to your needs. Our experienced consultants have in-depth knowledge of steam room and sauna design principles, functionality, and equipment selection. We will work closely with you to understand your preferences, available space, and budget, and provide customized recommendations that align with your vision. Whether you are looking to create a luxurious steam spa or a traditional sauna, we have the expertise to bring your ideas to life. During the consultation process, we will consider various factors such as ventilation, heating systems, seating options, and lighting to ensure optimal comfort and performance. We will also provide guidance on the selection of materials, including steam generators, sauna heaters, benches, and controls, sourced from reputable manufacturers known for their quality and reliability. Our goal is to create a steam room or sauna that not only meets your expectations but exceeds them. We prioritize functionality, aesthetics, and energy efficiency, ensuring that your steam and sauna experience is both invigorating and sustainable. With our consultation services, you can confidently embark on the journey of transforming your space into a haven of relaxation and rejuvenation. Our team of experts will be there every step of the way, from initial design concepts to the final installation, ensuring a seamless and satisfying experience. Unlock the ultimate relaxation and wellness benefits with our steam and sauna consultation services. Let Shreeji be your trusted partner in creating a customized steam and sauna experience that will enhance your well-being and elevate your lifestyle ",
  },
  {
    serviceId: 17,
    serviceName: "Play Equpiments",
    serviceDesc:
      "At Shreeji, we believe that every child deserves a safe and stimulating play environment. That's why we offer a wide range of premium Swimming pool and playground equipment designed to inspire imagination, encourage physical activity, and provide endless fun for children of all ages. Our play equipment is crafted with utmost care and attention to detail, ensuring the highest standards of safety, durability, and quality. our extensive selection offers something for every child's interests and abilities. With Shreeji's premium playground equipment, you can create a vibrant and engaging play space that sparks the imaginations of children and promotes their physical, social, and cognitive development. We are committed to providing you with exceptional products and outstanding customer service, making us your trusted partner in creating joyful play experiences. Choose Shreeji for top-quality playground equipment that combines safety, durability, and fun, and let the laughter and excitement of children fill your play space",
  },
];
